### ISSUE TITLE
Typo in run.sh breaks configuration persistency

### ISSUE THREAD

**Issue by x86dev** [dell-cloud-marketplace/docker-phpbb#3]
A typo in your run.sh breaks the configuration persistency when using volumes for the **/var/www/html** directory:

The variable name **$APPLICATON_HOME** must be named **$APPLICATION_HOME** (missing 'I', line 17).
After fixing this, persistence across restarts is fine.

**Comment by sakrai** [comment]
I have added the fix to the master branch and is currently in 1.2 tag as well. The update has also been pushed to dockerhub.
